/*
  Copyright (c) 2008, Adobe Systems Incorporated
  All rights reserved.

  Redistribution and use in source and binary forms, with or without 
  modification, are permitted provided that the following conditions are
  met:

  * Redistributions of source code must retain the above copyright notice, 
    this list of conditions and the following disclaimer.
  
  * Redistributions in binary form must reproduce the above copyright
    notice, this list of conditions and the following disclaimer in the 
    documentation and/or other materials provided with the distribution.
  
  * Neither the name of Adobe Systems Incorporated nor the names of its 
    contributors may be used to endorse or promote products derived from 
    this software without specific prior written permission.

  THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS
  IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO,
  THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR
  PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT OWNER OR 
  CONTRIBUTORS BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL,
  EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO,
  PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR
  PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF
  LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING
  NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS
  SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
*/

package com.adobe.growl
{	
	
	/**
	 * Class that represents a Growl notification.
	 */
	public class Notification
	{		
		/**
		 * The notification name. This must match a notification name which
		 * has been registered with the Growl service.
		 * 
		 * This property is required by the Growl service.
		 */
		public var name:String;
		
		/**
		 * Notification title. This will be displayed in the Growl notification.
		 * 
		 * This property is required by the Growl service.
		 */
		public var title:String;
		
		/**
		 * Notification message. If set, this will be displayed in the Growl 
		 * notification.
		 */
		public var text:String = "";
		
		/**
		 * Whether the notification will be sticky and stay on screen until the
		 * user manually dismisses it.
		 */
		public var sticky:Boolean = false;
		
		/**
		 * Path to the icon / image, which if set, will be displayed within the
		 * notification.
		 * 
		 * The path can be specified as an HTTP or FILE URI.
		 */
		public var iconPath:String;

		/**
		 * Specifies the priority of the notification.
		 * 
		 * Valid values are whole number greater than or equal to -2 and less than
		 * or equal to 2.
		 */		
		public var priority:int = 0;
		
		private var _id:String;
		
		/**
		 * 	Constructor
		 */
		public function Notification()
		{
			_id = String((new Date().time) + Math.floor(Math.random()));
		}
		
		/**
		 * Array of custom X- Header instances which will be included with the Growl
		 * service request and returned with the response.
		 * 
		 * Custom header names must be in the form of X-HEADERNAME
		 * 
		 * @see Header
		 */
		public var xHeaders:Array;
		
		/**
		 * The id that uniquely identifies the notification.
		 * 
		 * The id is automatically generated by the class.
		 */
		public function get id():String
		{
			return _id;
		}
	}
}